AWSTemplateFormatVersion: "2010-09-09"
Description: Creates the GOCD EC2 instance. This assumes a default VPC present with public subnets.

Parameters:
  securityKeyName:
    Type: String
    Description: The SSH key name
  tagName:
    Type: String
    Description: The training session name such as bootcamp-feb-2018 or extended-paatshala-march-2018  

Mappings:
  regionMap:
      "us-east-1": 
        AMI: "ami-97785bed"
      "us-east-2": 
        AMI: "ami-f63b1193"
      "us-west-2": 
        AMI: "ami-f2d3638a"
      "us-west-1": 
        AMI: "ami-824c4ee2"
      "ap-southeast-1": 
        AMI: "ami-68097514"
      "ap-southeast-2": 
        AMI: "ami-942dd1f6"
      "ap-south-1": 
        AMI: "ami-531a4c3c"
      "cn-north-1": 
        AMI: "ami-cb19c4a6"


Resources:
  SecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupName: !Join [ "-", [ "GOCD-Box-SecurityGroup", Ref: tagName ] ]
      GroupDescription: Allows SSH and 8154 port access to the GOCD box from the world.
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: '22'
        ToPort: '22'
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: '8154'
        ToPort: '8154'
        CidrIp: 0.0.0.0/0

  EC2:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: !Ref securityKeyName
      ImageId: !FindInMap [regionMap, !Ref "AWS::Region", AMI]
      #todo: need to change the below to a m5.large
      InstanceType: m5.large
      SecurityGroups:
        - !Ref SecurityGroup
      UserData:
        Fn::Base64:                               
          !Sub |
              #!/bin/bash -ex
              yum update -y
              yum install -y docker
              usermod -a -G docker ec2-user
              curl -L https://github.com/docker/compose/releases/download/1.9.0/docker-compose-`uname -s`-`uname -m` | sudo tee /usr/local/bin/docker-compose > /dev/null
              chmod +x /usr/local/bin/docker-compose
              service docker start
              chkconfig docker on
              curl https://raw.githubusercontent.com/Sethuraman/bootcamp-gocdinfra/master/docker/docker-compose.yml > docker-compose.yml
              /usr/local/bin/docker-compose up -d
              mkdir -p /.ssh && ssh-keygen -f /.ssh/id_rsa -t rsa -N '' && chown -R 1000:1000 /.ssh
              ssh-keyscan -t rsa github.com >> /.ssh/known_hosts

      Tags:
        - Key: Team
          Value: !Ref tagName     
  EBS:
    Type: AWS::EC2::Volume
    Properties:
      #todo: need to make this higher
      Size: 8
      AvailabilityZone: !GetAtt EC2.AvailabilityZone

  MountPoint:
    Type: AWS::EC2::VolumeAttachment
    Properties:
      InstanceId: !Ref EC2
      VolumeId: !Ref EBS
      Device: /dev/sdh

  IPAssoc:
    Type: AWS::EC2::EIPAssociation
    Properties:
      InstanceId: !Ref EC2
      EIP: 
        Fn::ImportValue: 
          !Join [ "-", [ "API-Box-IP", Ref: tagName ] ]